import { pgTable, text, real, timestamp } from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// Income Agent pipeline tables (mirrors the SQLite schema in income-agents/store.py)
// Prefixed with "income_" to avoid collisions with future tables.
// IDs are hex strings (sha1[:16]) generated by the Python agents.
// ---------------------------------------------------------------------------

export const opportunitiesTable = pgTable("income_opportunities", {
  id: text("id").primaryKey(),
  type: text("type").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull().default(""),
  url: text("url").notNull().default(""),
  source: text("source").notNull().default(""),
  valueUsd: real("value_usd").notNull().default(0),
  difficulty: text("difficulty").notNull().default("medium"),
  roiScore: real("roi_score").notNull().default(50),
  status: text("status").notNull().default("new"),
  metadata: text("metadata").notNull().default("{}"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const reviewQueueTable = pgTable("income_review_queue", {
  id: text("id").primaryKey(),
  opportunityId: text("opportunity_id").references(() => opportunitiesTable.id, { onDelete: "set null" }),
  outputType: text("output_type").notNull(),
  title: text("title").notNull().default(""),
  outputContent: text("output_content").notNull().default(""),
  metadata: text("metadata").notNull().default("{}"),
  status: text("status").notNull().default("pending"),
  rejectionNote: text("rejection_note").notNull().default(""),
  submissionUrl: text("submission_url").notNull().default(""),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  reviewedAt: timestamp("reviewed_at"),
});

export const incomeLogTable = pgTable("income_log", {
  id: text("id").primaryKey(),
  reviewId: text("review_id"),
  amountUsd: real("amount_usd").notNull().default(0),
  platform: text("platform").notNull().default(""),
  notes: text("notes").notNull().default(""),
  loggedAt: timestamp("logged_at").notNull().defaultNow(),
});

export type Opportunity = typeof opportunitiesTable.$inferSelect;
export type ReviewQueueItem = typeof reviewQueueTable.$inferSelect;
export type IncomeLog = typeof incomeLogTable.$inferSelect;
